name: Build site
on:
  workflow_dispatch:
  schedule:
    - cron:  '30 22 * * *'
jobs:
  build-site:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/setup-php-action
      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: json

      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build site
        run: |
          composer install --prefer-dist
          
          bin/console app:build:site
      - name: Commit and push changes
        run: |
          git config --global user.name 'robiningelbrecht'
          git config --global user.email 'robiningelbrecht@users.noreply.github.com'
          git add .
          git status
          git diff --staged --quiet || git commit -m"New site build"
          git push
      - name: ntfy.sh
        uses: robiningelbrecht/ntfy-action@v1.0.0
        if: always()
        with:
            url: ${{ secrets.NTFY_URL }}
            topic: ${{ secrets.NTFY_TOPIC }}
            icon: 'https://github.githubassets.com/images/modules/profile/achievements/starstruck-default.png'
            job_status: ${{ job.status }}
